name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore Restie/RestieAPI/RestieAPI.csproj
    - name: Build
      run: dotnet build Restie/RestieAPI/RestieAPI.csproj --no-restore
    - name: Publish
      run: dotnet publish Restie/RestieAPI/RestieAPI.csproj -c Release -o Restie/RestieAPI/RestieAPI/restieapi
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: restieapi
        path: Restie/RestieAPI/RestieAPI/restieapi
