name: .NET and Ionic React Deployment

on:
  push:
    branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore RestieAPI/RestieAPI/RestieAPI.csproj
      - name: Build
        run: dotnet build RestieAPI/RestieAPI/RestieAPI.csproj --no-restore
      - name: Publish
        run: dotnet publish RestieAPI/RestieAPI/RestieAPI.csproj -c Release -o RestieAPI/RestieAPI/restieapi
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: restieapi
          path: RestieAPI/RestieAPI/restieapi
          
  build-docker-image:
    runs-on: ubuntu-latest
    needs: build-dotnet
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/restieapi:latest
      working-directory: ./RestieAPI/RestieAPI

    - name: Push Docker image to Docker Hub
      run: docker push  ${{ secrets.DOCKER_USERNAME }}/restieapi:latest
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESSTOKEN }}
  deploy-ionic-react:
    runs-on: ubuntu-latest
    needs: build-docker-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.5.0' # Change the version according to your project
      - name: Build Ionic React app
        run: |
          cd RestieHardware/restie
          npm install
          npm run build
        # - name: Deploy to Hosting Service
        # Add your deployment commands here, such as deploying to Firebase, Netlify, GitHub Pages, or any other hosting service.
