name: .NET and Ionic React Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        env:
          GIT_SSH_COMMAND: 'ssh -v'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
          token: ${{ secrets.PAT_TOKEN }}
      - name: Restore dependencies
        run: dotnet restore RestieAPI/RestieAPI/RestieAPI.csproj
      - name: Build
        run: dotnet build RestieAPI/RestieAPI/RestieAPI.csproj --no-restore
      - name: Publish
        run: dotnet publish RestieAPI/RestieAPI/RestieAPI.csproj -c Release -o RestieAPI/RestieAPI/restieapi
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: restieapi
          path: RestieAPI/RestieAPI/restieapi

  deploy-ionic-react:
    # needs: build-dotnet
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Install dependencies
        run: npm install RestieHardware/restie # Install dependencies from the RestieHardware/restie repository

      - name: Debug SSH connection
        run: |
          echo "Checking SSH connection..."
          GIT_SSH_COMMAND="ssh -vvv" git ls-remote git@github.com:RestieHardware/restie.git
      - name: Build Ionic React app
        run: npm run build RestieHardware/restie
        # - name: Deploy to Hosting Service
        # Add your deployment commands here, such as deploying to Firebase, Netlify, GitHub Pages, or any other hosting service.
